logging:
  level:
    org.springframework.web.servlet: info
    org.hibernate.orm.jdbc.bind: trace

spring:
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USERNAME}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
    defer-datasource-initialization: true
#  sql.init.mode: always
---